# Generated by Django 5.1.6 on 2025-02-27 05:43

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='default@gmx.de', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('profileColor', models.CharField(default='#1FD7C1', max_length=30)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField(default='subtask', max_length=30)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@gmx.de', max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('description', models.TextField(default='beschreibung!')),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('feedback', 'Feedback'), ('todo', 'To Do'), ('progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('type', models.CharField(choices=[('technical_task', 'Technical Task'), ('user_story', 'User Story')], default='user_story', max_length=20)),
                ('assigned_to', models.ManyToManyField(blank=True, to='joinbackend_app.contact')),
                ('subtasks', models.ManyToManyField(blank=True, to='joinbackend_app.subtask')),
            ],
            options={
                'ordering': ['task_name'],
            },
        ),
    ]
