# Generated by Django 5.1.6 on 2025-02-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackend_app', '0002_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
    ]
