# Generated by Django 5.1.6 on 2025-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackend_app', '0003_alter_task_options_rename_task_name_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('todo', 'To Do'), ('progress', 'In Progress'), ('done', 'Done')], default='To Do', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], default='User Story', max_length=20),
        ),
    ]
