# Generated by Django 5.1.6 on 2025-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackend_app', '0004_contact_profilecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@gmx.de', max_length=254),
        ),
    ]
