# Generated by Django 5.1.6 on 2025-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackend_app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profileColor',
            field=models.CharField(default='#1FD7C1', max_length=30),
        ),
    ]
