# Generated by Django 5.1.6 on 2025-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackend_app', '0003_contact_email_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profileColor',
            field=models.CharField(default='#red', max_length=30),
        ),
    ]
