# Generated by Django 5.1.6 on 2025-02-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackend_app', '0004_alter_task_category_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, to='joinbackend_app.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, null=True, to='joinbackend_app.subtask'),
        ),
    ]
